/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    aws_project_region: "ap-southeast-2",
    aws_appsync_graphqlEndpoint: "https://xwq7fm5dhzcxndfbzbadt3zxha.appsync-api.ap-southeast-2.amazonaws.com/graphql",
    aws_appsync_region: "ap-southeast-2",
    aws_appsync_authenticationType: "AMAZON_COGNITO_USER_POOLS",
    aws_cognito_identity_pool_id: "ap-southeast-2:b71f4e0a-c244-4468-b65b-c1facac1d44c",
    aws_cognito_region: "ap-southeast-2",
    aws_user_pools_id: "ap-southeast-2_WMAnJcB4F",
    aws_user_pools_web_client_id: "3b3lv2g0vve2p3sutsqgmtqefk",
    oauth: {
        domain: "anystay7893a3c5-7893a3c5-dev.auth.ap-southeast-2.amazoncognito.com",
    },
    aws_cognito_username_attributes: ["EMAIL"],
    aws_cognito_social_providers: [],
    aws_cognito_signup_attributes: ["EMAIL"],
    aws_cognito_mfa_configuration: "OFF",
    aws_cognito_mfa_types: [],
    aws_cognito_password_protection_settings: {
        passwordPolicyMinLength: 8,
        passwordPolicyCharacters: [],
    },
    aws_cognito_verification_mechanisms: ["EMAIL", "PHONE_NUMBER"],
    aws_user_files_s3_bucket: "anystayd5a42d592a26430fa01b77cb5f594d9743601-dev",
    aws_user_files_s3_bucket_region: "ap-southeast-2",
};

export default awsmobile;
