/***************************************************
 * Generated by SVG Artista on 8/1/2023, 11:44:37 PM
 * MIT license (https://opensource.org/licenses/MIT)
 * W. https://svgartista.net
 **************************************************/

/* .logoSpinner {
    enable-background: new 0 0 356 356;
}

.logoSpinner .svg-elem-1 {
    stroke-dashoffset: 0;
    stroke-dasharray: 1395.0576171875px;
    -webkit-transition: stroke-dashoffset 0.5s cubic-bezier(0.47, 0, 0.745, 0.715) 0s;
    transition: stroke-dashoffset 0.5s cubic-bezier(0.47, 0, 0.745, 0.715) 0s;
}

.logoSpinner .active {
    stroke-dashoffset: 1395.0576171875px;
}

.st0 {
    fill: none;
    stroke: ${ColorTheme.Red.color};
    stroke-width: 26;
    stroke-linecap: round;
    stroke-miterlimit: 10;
} */

import styled from "styled-components";
import { ColorTheme } from "../../globaStyledComponents/globalStyledComponentsStyling";

interface spinnerStylingProps {
    reverse?: boolean;
    speedSeconds?: number;
    active?: boolean;
}

export const LogoSpinnerWrapper = styled.svg`
    enable-background: new 0 0 356 356;
`;
export const SvgPath = styled.path<spinnerStylingProps>`
    stroke-dashoffset: ${(props) => (props.reverse ? "1395.0576171875px" : 0)};
    stroke-dasharray: 1395.0576171875px;
    -webkit-transition: stroke-dashoffset ${(props) => (props.speedSeconds ? `${props.speedSeconds}s` : "1s")} cubic-bezier(0.47, 0, 0.745, 0.715) 0s;
    transition: stroke-dashoffset ${(props) => (props.speedSeconds ? `${props.speedSeconds}s` : "1s")} cubic-bezier(0.47, 0, 0.745, 0.715) 0s;
    fill: none;
    stroke: ${ColorTheme.Red.color};
    stroke-width: 26;
    stroke-linecap: round;
    stroke-miterlimit: 10;
    ${(props) =>
        props.active &&
        `
        stroke-dashoffset: ${props.reverse ? 0 : "1395.0576171875px"};
    `}
`;
